# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  issues:
    types:
      - opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  echo-in-console:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo ${{ github.event.issue.title }}
