# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  issues:
    types:
      - opened

jobs:
  play-game:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Load Python
        uses: actions/setup-python@v5.3.0

      - name: Run python print
        env:
          MOVEMENT: ${{ github.event.issue.title }}
          AUTOR: ${{ github.event.issue.user.login }}
        run: python main.py

      - name: Push to repo
        uses: stefanzweifel/git-auto-commit-action@v5
